<?php
/**
 * @file
 * Code for the Collabco Knowledge Feature feature.
 */

include_once 'collabco_knowledge_feature.features.inc';

/**
 * Implements hook_collabco_integration().
 */
function colabco_knowledge_feature_collabco_integration() {
  // Add links to views if a module wants to do that.
  return array(
    'collabco_knowledge_feature' => array(
      'views' => array(
        'library' => array(
          'group_page' => array(
            'subscribe_flag' => array(
              'group_type' => 'node',
              'entity_type' => 'none',
            ),
            'add_content_link' => array(
              'bundle' => 'knowledge_object',
              'areas' => array('header'),
            ),
          ),
        ),
      ),
    ),
  );
}
