<?php
/**
 * @file
 * Code for the Collabco Knowledge Feature feature.
 */

include_once 'collabco_knowledge_feature.features.inc';

/**
 * Impliments hook_field_widget_form_alter().
 */
function collabco_knowledge_feature_field_widget_form_alter(&$element, &$form_state, $context) {
  if (!empty($element['#field_name'])) {
    switch ($element['#field_name']) {
      // Fixes for file and entity ref fields. These could possibly go in the 
      // knowledge feature instead of here...
      case 'field_ko_file':
        unset($element['#theme_wrappers']);
        unset($element['#description']);
        $element['#file_upload_description'] = '';
        break;
      case 'field_ko_ref':
        $help = t('Or select a file you have already uploaded elsewhere');
        $element['#field_prefix'] = $help;
        break;
    }
  }
}

/**
 * Implements hook_collabco_integration().
 */
function collabco_knowledge_feature_collabco_integration() {
  // Add links to views if a module wants to do that.
  return array(
    'collabco_knowledge_feature' => array(
      'entity' => array(
        'node'=> array(
          'knowledge_object' => array(
            'add_content_link' => TRUE,
            'tab' => array(
              'Library' => array(
                'subpath' => 'library',
              ),
            ),
          )
        ),
      ),
      'views' => array(
        'library' => array(
          'group_page' => array(
            'subscribe_flag' => array(
              'group_type' => 'node',
              'entity_type' => 'none',
            ),
            'add_content_link' => array(
              'areas' => array('header'),
            ),
          ),
        ),
      ),
    ),
  );
}

